DROP TABLE IF EXISTS superheroe;

CREATE TABLE superheroe (
       id bigint generated by default as identity,
        nombre varchar(50) not null,
        tipo varchar(50),
        primary key (id)
    );
	
INSERT INTO Superheroe (nombre, tipo) VALUES
  ('Spiderman', 'Marvel'),
  ('Ironman', 'Marvel'),
  ('Thor', 'Marvel'),
  ('Capitan America', 'Marvel'),
  ('Batman', 'Dc Comic'),
  ('Aquaman', 'Dc Comic')
  ;